run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - durationcheck
    - gocritic
    - misspell
    - prealloc

linters-settings:
  errcheck:
    check-blank: true
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go$
      linters:
        - errcheck
        - gocritic
