import LegalLayout from '../layout'

export default function TermsOfServicePage() {
  return (
    <LegalLayout title="Terms of Service" effectiveDate="July 25, 2026">
      <h2 className="text-xl font-semibold mt-8 mb-4" style={{ color: 'var(--text-primary)' }}>1. Acceptance of Terms</h2>
      <p className="mb-4 leading-relaxed">
        By accessing or using the NOANT platform ("Service"), you agree to be bound by these Terms of Service ("Terms").
        If you are using the Service on behalf of an organization, you represent that you have the authority to bind
        that organization to these Terms. If you do not agree to these Terms, do not use the Service.
      </p>
      <p className="mb-4 leading-relaxed">
        We reserve the right to modify these Terms at any time. Material changes will be communicated via email or
        in-app notification at least 30 days before taking effect. Continued use of the Service after changes take
        effect constitutes acceptance of the updated Terms.
      </p>

      <h2 className="text-xl font-semibold mt-8 mb-4" style={{ color: 'var(--text-primary)' }}>2. Definitions</h2>
      <ul className="list-disc pl-6 space-y-2 mb-4">
        <li><strong>"Service"</strong> means the NOANT AI customer support platform, including all web applications, APIs, dashboards, integrations, and related features.</li>
        <li><strong>"User," "you," or "your"</strong> means any individual or entity that accesses or uses the Service.</li>
        <li><strong>"Account"</strong> means your registered account on the Service.</li>
        <li><strong>"Content"</strong> means all data, text, files, information, and materials uploaded, submitted, or transmitted through the Service.</li>
        <li><strong>"Customer Data"</strong> means data belonging to you or your end users that is processed through the Service.</li>
        <li><strong>"End User"</strong> means any individual who interacts with your AI agent or chatbot deployed through the Service.</li>
        <li><strong>"AI Output"</strong> means responses, recommendations, or content generated by the Service's artificial intelligence systems.</li>
        <li><strong>"Integration"</strong> means any third-party platform (e.g., WhatsApp, Telegram) connected to the Service.</li>
      </ul>

      <h2 className="text-xl font-semibold mt-8 mb-4" style={{ color: 'var(--text-primary)' }}>3. Eligibility</h2>
      <p className="mb-4 leading-relaxed">
        You must be at least 18 years old (or the age of majority in your jurisdiction) to use the Service. By using
        the Service, you represent and warrant that you meet this requirement and have the legal capacity to enter
        into a binding agreement.
      </p>

      <h2 className="text-xl font-semibold mt-8 mb-4" style={{ color: 'var(--text-primary)' }}>4. Account Registration and Security</h2>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>4.1 Registration</h3>
      <p className="mb-4 leading-relaxed">
        To use the Service, you must create an Account by providing accurate, current, and complete information.
        You agree to update your information as necessary to maintain its accuracy.
      </p>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>4.2 Account Security</h3>
      <p className="mb-4 leading-relaxed">
        You are responsible for maintaining the confidentiality of your Account credentials, all activities that occur
        under your Account, and immediately notifying us of any unauthorized access or security breach. We are not
        liable for any loss or damage arising from your failure to secure your Account.
      </p>

      <h2 className="text-xl font-semibold mt-8 mb-4" style={{ color: 'var(--text-primary)' }}>5. Description of Service</h2>
      <p className="mb-4 leading-relaxed">
        NOANT provides an AI-powered customer support platform that enables businesses to deploy AI chatbots across
        multiple communication channels, automate customer support responses using machine learning, manage customer
        conversations and knowledge bases, integrate with messaging platforms, and access analytics and reporting.
      </p>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>5.1 AI-Generated Content</h3>
      <p className="mb-4 leading-relaxed">
        The Service uses artificial intelligence to generate responses. You acknowledge that AI Output may not always
        be accurate, complete, or appropriate. You are solely responsible for reviewing and approving AI-generated
        responses before they are sent to End Users. AI Output should not be considered professional advice.
      </p>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>5.2 Beta Features</h3>
      <p className="mb-4 leading-relaxed">
        We may offer beta or experimental features. Beta features are provided "as is" without warranties, and we
        may discontinue them at any time without notice.
      </p>

      <h2 className="text-xl font-semibold mt-8 mb-4" style={{ color: 'var(--text-primary)' }}>6. Subscriptions and Payment</h2>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>6.1 Plans</h3>
      <p className="mb-4 leading-relaxed">
        The Service is offered under various subscription tiers as described on our pricing page. Features, limits,
        and pricing are subject to change with 30 days' notice.
      </p>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>6.2 Payment</h3>
      <p className="mb-4 leading-relaxed">
        All fees are quoted in the currency displayed at the time of purchase. Payment is due in advance on a monthly
        or annual basis. You authorize us to charge your designated payment method for all applicable fees. All fees
        are non-refundable except as expressly stated in these Terms.
      </p>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>6.3 Free Tier</h3>
      <p className="mb-4 leading-relaxed">
        If you are using a free tier or trial, we may limit features, usage, or duration at our discretion. We may
        discontinue the free tier at any time without notice.
      </p>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>6.4 Late Payments</h3>
      <p className="mb-4 leading-relaxed">
        Overdue payments will incur interest at the rate of 1.5% per month (or the maximum rate permitted by law,
        whichever is lower). We reserve the right to suspend your access to the Service for overdue payments after
        a 7-day grace period.
      </p>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>6.5 Taxes</h3>
      <p className="mb-4 leading-relaxed">
        All fees are exclusive of applicable taxes. You are responsible for paying any taxes associated with your use
        of the Service, including VAT, GST, or sales tax as applicable in your jurisdiction.
      </p>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>6.6 Refund Policy</h3>
      <p className="mb-4 leading-relaxed">
        Monthly subscriptions: No refunds for partial months. Annual subscriptions: Pro-rated refund within the first
        30 days if you have not used the Service in a material way. All refund requests must be submitted to
        legal@noant.com within the applicable period.
      </p>

      <h2 className="text-xl font-semibold mt-8 mb-4" style={{ color: 'var(--text-primary)' }}>7. Your Content and Data</h2>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>7.1 Ownership</h3>
      <p className="mb-4 leading-relaxed">
        You retain all rights, title, and interest in and to your Content and Customer Data. We do not claim
        ownership over any materials you upload to the Service.
      </p>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>7.2 License Grant</h3>
      <p className="mb-4 leading-relaxed">
        By using the Service, you grant us a limited, non-exclusive, worldwide license to host, store, process, and
        display your Content solely for the purpose of providing and improving the Service.
      </p>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>7.3 Training Data</h3>
      <p className="mb-4 leading-relaxed">
        You may upload content to train your AI agent. This content remains your property, is used exclusively for
        your AI agent's responses, is not shared with other customers, and is not used to train general AI models
        without your explicit consent.
      </p>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>7.4 Data Deletion</h3>
      <p className="mb-4 leading-relaxed">
        You may delete your Content at any time through the Service. Upon deletion, data is removed from active
        systems within 30 days. Data may persist in backups for up to 90 days before permanent deletion.
      </p>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>7.5 Content Restrictions</h3>
      <p className="mb-4 leading-relaxed">
        You agree not to upload Content that violates any applicable law, infringes intellectual property rights,
        contains malware, is defamatory or threatening, promotes discrimination, or violates third-party terms of
        service. We reserve the right to remove violating Content without notice.
      </p>

      <h2 className="text-xl font-semibold mt-8 mb-4" style={{ color: 'var(--text-primary)' }}>8. Acceptable Use Policy</h2>
      <p className="mb-4 leading-relaxed">You agree not to use the Service to:</p>
      <ol className="list-decimal pl-6 space-y-2 mb-4">
        <li>Engage in any activity that violates applicable law or regulation</li>
        <li>Send harassing, threatening, or abusive messages through the Service</li>
        <li>Send unsolicited bulk messages or spam through any Integration</li>
        <li>Impersonate any person or entity, or falsely represent your affiliation</li>
        <li>Attempt to disrupt, overload, or compromise the Service's infrastructure</li>
        <li>Decompile, disassemble, or reverse-engineer any part of the Service</li>
        <li>Use automated tools to scrape, crawl, or extract data from the Service</li>
        <li>Resell, sublicense, or distribute the Service without written authorization</li>
        <li>Bypass any rate limits, access controls, or security measures</li>
        <li>Represent AI-generated responses as human-written to deceive End Users, where such deception violates consumer protection laws</li>
      </ol>
      <p className="mb-4 leading-relaxed">
        Violations may result in immediate suspension or termination of your Account without prior notice.
      </p>

      <h2 className="text-xl font-semibold mt-8 mb-4" style={{ color: 'var(--text-primary)' }}>9. Third-Party Integrations</h2>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>9.1 WhatsApp and Messaging Platforms</h3>
      <p className="mb-4 leading-relaxed">
        The Service integrates with third-party messaging platforms. Your use of these Integrations is subject to
        their respective terms of service, including the WhatsApp Business Policy and Commerce Policy.
      </p>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>9.2 Third-Party Providers</h3>
      <p className="mb-4 leading-relaxed">
        We may use third-party service providers to facilitate Integrations. We are not responsible for the
        availability, accuracy, or practices of third-party services.
      </p>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>9.3 Integration Responsibility</h3>
      <p className="mb-4 leading-relaxed">
        You are solely responsible for obtaining all necessary authorizations for Integrations, ensuring compliance
        with their terms, and managing Opt-Out requests from End Users in compliance with applicable laws.
      </p>

      <h2 className="text-xl font-semibold mt-8 mb-4" style={{ color: 'var(--text-primary)' }}>10. Intellectual Property</h2>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>10.1 Our IP</h3>
      <p className="mb-4 leading-relaxed">
        The Service, including all software, designs, logos, trademarks, documentation, and related materials, is
        owned by NOANT and protected by intellectual property laws. Nothing grants you any right to use our
        trademarks, logos, or brand names without prior written consent.
      </p>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>10.2 Feedback</h3>
      <p className="mb-4 leading-relaxed">
        If you provide feedback, suggestions, or ideas about the Service, you grant us a perpetual, irrevocable,
        worldwide, royalty-free license to use, modify, and incorporate such feedback into the Service.
      </p>

      <h2 className="text-xl font-semibold mt-8 mb-4" style={{ color: 'var(--text-primary)' }}>11. Privacy and Data Protection</h2>
      <p className="mb-4 leading-relaxed">
        Our collection and use of personal information is governed by our{' '}
        <a href="/privacy" className="underline hover:text-primary transition-colors">Privacy Policy</a>, which is
        incorporated into these Terms by reference. If you are located in the EEA, UK, or Switzerland, we process
        personal data in accordance with the GDPR. Our Data Processing Agreement is available upon request.
      </p>

      <h2 className="text-xl font-semibold mt-8 mb-4" style={{ color: 'var(--text-primary)' }}>12. Service Level and Availability</h2>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>12.1 Uptime</h3>
      <p className="mb-4 leading-relaxed">
        We target 99.9% uptime for paid plans, measured on a monthly basis. Scheduled maintenance windows are
        excluded and will be communicated at least 48 hours in advance when possible.
      </p>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>12.2 Service Credits</h3>
      <p className="mb-4 leading-relaxed">
        If uptime falls below 99.9% in a given month, you may request a service credit equal to 10% of your monthly
        fee. Service credits are your sole and exclusive remedy for uptime failures.
      </p>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>12.3 Support</h3>
      <p className="mb-4 leading-relaxed">
        We provide support via email at support@noant.com. Response time: within 24 hours for standard plans;
        within 4 hours for enterprise plans.
      </p>

      <h2 className="text-xl font-semibold mt-8 mb-4" style={{ color: 'var(--text-primary)' }}>13. Limitation of Liability</h2>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>13.1 Disclaimer of Warranties</h3>
      <p className="mb-4 leading-relaxed">
        THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED,
        INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
        NON-INFRINGEMENT, AND ACCURACY. We do not warrant that the Service will be uninterrupted, secure, or
        error-free, that AI Output will be accurate or reliable, or that defects will be corrected.
      </p>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>13.2 Limitation of Damages</h3>
      <p className="mb-4 leading-relaxed">
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, NOANT SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
        CONSEQUENTIAL, OR PUNITIVE DAMAGES. Our total aggregate liability shall not exceed the greater of: (a) the
        amounts paid by you in the twelve (12) months preceding the claim, or (b) one hundred US dollars ($100.00).
      </p>

      <h2 className="text-xl font-semibold mt-8 mb-4" style={{ color: 'var(--text-primary)' }}>14. Indemnification</h2>
      <p className="mb-4 leading-relaxed">
        You agree to indemnify, defend, and hold harmless NOANT and its officers, directors, employees, and agents
        from any claims, liabilities, damages, losses, and expenses arising from your use of the Service, your
        violation of these Terms, your Content, your violation of third-party rights, or your failure to comply
        with applicable laws.
      </p>

      <h2 className="text-xl font-semibold mt-8 mb-4" style={{ color: 'var(--text-primary)' }}>15. Termination</h2>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>15.1 By You</h3>
      <p className="mb-4 leading-relaxed">
        You may terminate your Account at any time using the Account settings page or by contacting support@noant.com.
      </p>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>15.2 By Us</h3>
      <p className="mb-4 leading-relaxed">
        We may suspend or terminate your Account if you breach these Terms, your payment method fails, we are
        required by law, or we reasonably believe your use poses a security risk.
      </p>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>15.3 Effect of Termination</h3>
      <p className="mb-4 leading-relaxed">
        Upon termination, your right to use the Service ceases immediately. We will provide a 30-day export period
        for your data upon written request. After 30 days, your data will be permanently deleted.
      </p>

      <h2 className="text-xl font-semibold mt-8 mb-4" style={{ color: 'var(--text-primary)' }}>16. General Provisions</h2>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>16.1 Governing Law</h3>
      <p className="mb-4 leading-relaxed">
        These Terms are governed by the laws of the Federal Republic of Nigeria, without regard to conflict of law
        principles. The UN Convention on Contracts for the International Sale of Goods (CISG) does not apply.
      </p>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>16.2 Dispute Resolution</h3>
      <p className="mb-4 leading-relaxed">
        Disputes shall first be resolved through good-faith negotiation within 30 days. If negotiation fails, disputes
        shall be resolved through binding arbitration administered by the Lagos Court of Arbitration in Lagos, Nigeria.
      </p>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>16.3 Class Action Waiver</h3>
      <p className="mb-4 leading-relaxed">
        You agree to resolve disputes on an individual basis and waive your right to participate in class actions,
        class arbitrations, or representative proceedings.
      </p>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>16.4 Severability</h3>
      <p className="mb-4 leading-relaxed">
        If any provision is found unenforceable, that provision shall be enforced to the maximum extent permissible,
        and the remaining provisions shall remain in full force.
      </p>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>16.5 Entire Agreement</h3>
      <p className="mb-4 leading-relaxed">
        These Terms, together with the Privacy Policy and any applicable Data Processing Agreement, constitute the
        entire agreement between you and NOANT regarding the Service.
      </p>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>16.6 Assignment</h3>
      <p className="mb-4 leading-relaxed">
        You may not assign these Terms without our prior written consent. We may assign these Terms in connection
        with a merger, acquisition, or sale of assets.
      </p>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>16.7 Force Majeure</h3>
      <p className="mb-4 leading-relaxed">
        We shall not be liable for failure or delay resulting from causes beyond our reasonable control, including
        natural disasters, pandemics, war, terrorism, government actions, power failures, or internet disruptions.
      </p>
      <h3 className="text-lg font-medium mt-6 mb-3" style={{ color: 'var(--text-primary)' }}>16.8 Notices</h3>
      <p className="mb-4 leading-relaxed">
        Notices to you may be sent via email, in-app notifications, or by posting on our website. Notices to us
        must be sent to legal@noant.com.
      </p>
    </LegalLayout>
  )
}
